name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy bot to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Set Railway token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "Railway token o'rnatildi"

      - name: Deploy to Railway
        run: |
          railway link --project magnificent-simplicity
          railway up --service elshift-telegram-bot.railway.internal --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
